production:
  adapter: postgresql
  encoding: unicode
  database: ENV['DATABASE']
  pool: 5
  username: ENV['USER']
  password: ENV['PASSWORD']
  port: ENV['PORT']
  host: ENV['HOST']

development:
  adapter: postgresql
  encoding: unicode
  database: warehouse_app_development
  pool: 5
  username: warehouse_app
  password: 887983

test:
  adapter: postgresql
  encoding: unicode
  database: warehouse_app_test
  pool: 5
  username: warehouse_app
  password: 887983
